---
- name: Starts a VM
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    resource_group: group
    vm_name: name
    client: clientid
    secret: clientsecret
    sub: subid
    tenant: tenant


  tasks:
  - name: Start the instance
    azure_rm_virtualmachine:
      client_id: "{{ client }}"
      secret: "{{ secret }}"
      subscription_id: "{{ sub }}"
      tenant: "{{ tenant }}"
      resource_group: "{{ resource_group }}"    
      name: "{{ vm_name }}"
      state: present
      started: yes
      
