---
- name: subscribe the host to rhn
  vars:
  hosts: "{{ ipa_host }}"  
  redhat_subscription:
    state: present
    username: "{{ rhn_username }}"
    password: "{{ rhn_password }}"
    pool_ids: "{{ pool_id }}"
