---
- name: Install EPEL repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  delegate_to: "{{ control_machine }}"    

- name: Install Ansible
  yum:
    name: ansible
    state: present
  delegate_to: "{{ control_machine }}"        