---
- name: capture master public key during cluster expansion
  shell: "cat ~/.ssh/id_rsa.pub"  
  register: pubkey
  delegate_to: "{{ hostvars[inventory_hostname]['ocp-master'] }}"

- name: add key to authorized keys
  authorized_key: 
    user: "{{ ansible_user }}"
    state: present
    key: "{{ pubkey.stdout }}"