---
- name: Terminate instance in AWS EC2
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    access_key: accesskey
    secret_key: secretkey
    instance_id: instance
    region: us-east-1
    
  tasks:
  - name: Destroy
    ec2:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"    
      state: 'absent'
      instance_ids: "{{ instance_id }}"
      region: "{{ region }}"
