---
- name: Provision instance in AWS EC2
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    access_key: accesskey
    secret_key: secretkey
    subnet: subnet
    aws_region: us-east-1

  tasks:  
  - name: Gather instance facts
    ec2_instance_facts:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"    
      region: "{{ aws_region }}"
      validate_certs: False
    register: vms

  - debug:
      var: vms.instances

  - name: Stop instances
    ec2:
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      instance_ids: "{{ item.instance_id }}"
      wait: True
      vpc_subnet_id: "{{ subnet }}"
      region: "{{ aws_region }}"
      state: stopped
    with_items: vms.instances