---
- name: Installs packages via yum. Use an asterisk (*) to perform a yum -y update
  hosts: all
  remote_user: cloud-user
  become: yes
  vars: 
    packages: "httpd"
  
  tasks:
  - name: Install one or more packages
    yum:
      name: "{{packages}}"
...
