---
- name: create ssh key
  shell: echo -e  'y\n' | ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  when: inventory_hostname == groups['masters'][0]

- name: capture master public key during cluster install
  shell: "cat ~/.ssh/id_rsa.pub"  
  register: pubkey
  delegate_to: "{{ groups['masters'][0] }}"

- name: add key to authorized keys
  authorized_key: 
    user: "{{ ansible_user }}"
    state: present
    key: "{{ pubkey.stdout }}"
  
   
