---
- name: Show OS and kernel information
  hosts: all
  gather_facts: no

  tasks:
    - name: Get Red Hat version
      raw: cat /etc/redhat-release ; uname -r       
      register: version

    - debug:
        msg: "{{ inventory_hostname }},{{ version.stdout_lines[0] }},{{ version.stdout_lines[1] }}"
