---
- name: Show OS and kernel information
  hosts: all
  
  tasks:
  - debug:
      var: hostvars[inventory_hostname]
            
  - debug:
      msg: "Red Hat Enterprise Linux {{ hostvars[inventory_hostname]['ansible_distribution_version'] }} ({{ hostvars[inventory_hostname]['ansible_distribution_release'] }})"
      
  - debug:
      msg: "Kernel: {{ hostvars[inventory_hostname]['ansible_kernel'] }}"
      
