---
- name: Get the next available IP from Infoblox
  hosts: all
  gather_facts: False
  remote_user: cloud-user
  vars:
    control_machine: cfme-w4
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
  tasks:
  roles:
    - { role: infoblox }
